### ISSUE TITLE
Pilet debug crashes with "RangeError: Invalid WebSocket frame: invalid status code 22373" 

### ISSUE THREAD

**Issue by andrashatvani** [smapiot/piral#364]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [-] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

MacOS 11.3 Beta (20E5196f), Safari 14.1 (16611.1.18.1.2), piral-cli and piral-cli-webpack 0.12.4

## Description
The app uses Keycloak and on first access to the pilet after authentication `pilet debug` crashes with the following stack trace:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: invalid status code 22373
    at Receiver.controlMessage (/Users/work/IdeaProjects/wrwks/smp/smp-controlling-ui/node_modules/kras/dist/server/index.js:52619:18)
    at Receiver.getData (/Users/work/IdeaProjects/wrwks/smp/smp-controlling-ui/node_modules/kras/dist/server/index.js:52507:42)
    at Receiver.startLoop (/Users/work/IdeaProjects/wrwks/smp/smp-controlling-ui/node_modules/kras/dist/server/index.js:52311:22)
    at Receiver._write (/Users/work/IdeaProjects/wrwks/smp/smp-controlling-ui/node_modules/kras/dist/server/index.js:52247:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/Users/work/IdeaProjects/wrwks/smp/smp-controlling-ui/node_modules/kras/dist/server/index.js:20847:35)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/Users/work/IdeaProjects/wrwks/smp/smp-controlling-ui/node_modules/kras/dist/server/index.js:20752:13)
    at Receiver.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  [Symbol(status-code)]: 1002
```

## Steps to Reproduce

1. Start `pilet debug`
2. Load URL
3. Authenticate with Keycloak
4. Click on link to pilet in the browser

## Expected behavior

The pilet's page will be loaded.

## Actual behavior

The app crashes.

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Can you provide a simple MWE? Right now there is no way we can investigate this.
